[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "libmonado-bindings"
version = "0.1.0"
description = "Python bindings for the Monado XR service"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
    {name = "TheBlowxy"}
]
keywords = ["monado", "vr", "xr", "openxr", "bindings"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
]

[tool.setuptools]
# Das sorgt dafür, dass der gesamte Ordner inkl. aller .py Dateien bwee-rücksichtigt wird
packages = ["libmonado_bindings"]